version: "3.8"

services:
  finops-app:
    build: .
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.finops.rule=Host(`finops.cscloudsolutions.com.ar`)"
      - "traefik.http.routers.finops.entrypoints=websecure"
      - "traefik.http.routers.finops.tls.certresolver=mytlschallenge"
      - "traefik.http.services.finops.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy_network"
    networks:
      - proxy_network
      - finops_internal
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always
    networks:
      - finops_internal

networks:
  proxy_network:
    external: true
  finops_internal:
