CREATE TABLE IF NOT EXISTS AzureSearchSnapshots (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tenantId CHAR(36) NOT NULL,
  snapshotDate DATE NOT NULL,
  resourceId VARCHAR(500) NOT NULL,
  resourceName VARCHAR(255) NOT NULL,
  resourceGroup VARCHAR(255) NOT NULL,
  region VARCHAR(100) NOT NULL,
  skuName VARCHAR(50) NOT NULL,
  replicaCount INT DEFAULT 1,
  partitionCount INT DEFAULT 1,
  totalSearchUnits INT GENERATED ALWAYS AS (replicaCount * partitionCount) STORED,
  indexCount INT DEFAULT 0,
  documentCount BIGINT DEFAULT 0,
  storageGB DECIMAL(12, 2) DEFAULT 0,
  monthlyCostUSD DECIMAL(12, 2) DEFAULT 0,
  costBreakdown_compute DECIMAL(12, 2) DEFAULT 0,
  costBreakdown_storage DECIMAL(12, 2) DEFAULT 0,
  costBreakdown_queries DECIMAL(12, 2) DEFAULT 0,
  usage_qps DECIMAL(10, 2) DEFAULT 0,
  usage_latencyMs DECIMAL(10, 2) DEFAULT 0,
  usage_throttledPercent DECIMAL(5, 2) DEFAULT 0,
  usage_semanticQueriesDaily INT DEFAULT 0,
  utilizationPercent INT DEFAULT 0,
  lastAccessedDaysAgo INT DEFAULT NULL,
  isOrphaned BOOLEAN DEFAULT FALSE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_tenant_resource_date (tenantId, resourceId, snapshotDate),
  INDEX idx_tenant_date (tenantId, snapshotDate),
  INDEX idx_tenant_resource (tenantId, resourceId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
