export const kqlCatalog: Record<string, string> = {
  allVirtualMachines: `Resources | where type =~ 'microsoft.compute/virtualmachines' | project id, name, location, resourceGroup, subscriptionId, tags, powerState = tostring(properties.extended.instanceView.powerState.code)`,
  devVirtualMachines: `Resources | where type =~ 'microsoft.compute/virtualmachines' | where tags.Environment =~ 'Dev' or tags.Environment =~ 'Test' | project id, name, location, resourceGroup, subscriptionId, tags, powerState = tostring(properties.extended.instanceView.powerState.code)`,
  staleSnapshots: `Resources | where type =~ 'microsoft.compute/snapshots' | where properties.timeCreated < ago(30d) | project id, name, location, resourceGroup, subscriptionId, sizeGB=properties.diskSizeGB`,
  taggingNonCompliance: `Resources | where isnull(tags.CostCenter) or isnull(tags.Owner) or isnull(tags.Environment) | project id, name, type, location, resourceGroup, subscriptionId`,
  unattachedDisks: `Resources | where type =~ 'microsoft.compute/disks' | where properties.diskState == 'Unattached' | where properties.timeCreated < ago(14d) | project id, name, location, resourceGroup, subscriptionId, sku=sku.name, diskSizeGB=properties.diskSizeGB`,
  unusedIps: `Resources | where type =~ 'microsoft.network/publicipaddresses' | where properties.ipConfiguration == '' or isnull(properties.ipConfiguration) | where properties.timeCreated < ago(14d) | project id, name, location, resourceGroup, subscriptionId, sku=sku.name`,
  orphanedNics: `Resources | where type =~ 'microsoft.network/networkinterfaces' | where isnull(properties.virtualMachine) | project id, name, location, resourceGroup, subscriptionId`,
  orphanedNsgs: `Resources | where type =~ 'microsoft.network/networksecuritygroups' | where isnull(properties.networkInterfaces) and isnull(properties.subnets) | project id, name, location, resourceGroup, subscriptionId`,
  emptyAppServicePlans: `resources | where type =~ 'microsoft.web/serverfarms' | project serverFarmId = tolower(id), id, name, location, resourceGroup, subscriptionId, sku=sku.name | join kind=leftouter (resources | where type =~ 'microsoft.web/sites' | project siteId=id, serverFarmId = tolower(properties.serverFarmId)) on serverFarmId | summarize siteCount = countif(siteId != '') by id, name, location, resourceGroup, subscriptionId, sku | where siteCount == 0`,

  availabilitySets: `Resources | where type =~ 'microsoft.compute/availabilitysets' | where isnull(properties.virtualMachines) or array_length(properties.virtualMachines) == 0 | project id, name, location, resourceGroup, subscriptionId`,
  elasticPools: `resources | where type =~ 'microsoft.sql/servers/elasticpools' | project elasticPoolId = tolower(id), id, name, resourceGroup, location, subscriptionId, tags, properties | join kind=leftouter (resources | where type =~ 'Microsoft.Sql/servers/databases' | project dbId=id, properties | extend elasticPoolId = tolower(properties.elasticPoolId)) on elasticPoolId | summarize databaseCount = countif(dbId != '') by id, name, resourceGroup, location, subscriptionId | where databaseCount == 0`,
  routeTables: `Resources | where type =~ 'microsoft.network/routetables' | where isnull(properties.subnets) or array_length(properties.subnets) == 0 | project id, name, location, resourceGroup, subscriptionId`,
  loadBalancers: `Resources | where type =~ 'microsoft.network/loadbalancers' | where isnull(properties.backendAddressPools) or array_length(properties.backendAddressPools) == 0 | project id, name, location, resourceGroup, subscriptionId`,
  frontDoorWaf: `resources | where type =~ "microsoft.network/frontdoorwebapplicationfirewallpolicies" | where properties.securityPolicyLinks == "[]" | project id, name, location, resourceGroup, subscriptionId`,
  trafficManager: `resources | where type =~ "microsoft.network/trafficmanagerprofiles" | where properties.endpoints == "[]" | project id, name, location, resourceGroup, subscriptionId`,
  appGateways: `resources | where type =~ 'microsoft.network/applicationgateways' | extend backendPoolsCount = array_length(properties.backendAddressPools), AppGwId = tostring(id) | project AppGwId, resourceGroup, location, subscriptionId, name | join (resources | where type =~ 'microsoft.network/applicationgateways' | mvexpand backendPools = properties.backendAddressPools | extend backendIPCount = array_length(backendPools.properties.backendIPConfigurations) | extend backendAddressesCount = array_length(backendPools.properties.backendAddresses) | extend AppGwId = tostring(id) | summarize backendIPCount = sum(backendIPCount) ,backendAddressesCount=sum(backendAddressesCount) by AppGwId) on AppGwId | where (backendIPCount == 0 or isempty(backendIPCount)) and (backendAddressesCount==0 or isempty(backendAddressesCount)) | project id=AppGwId, name, location, resourceGroup, subscriptionId`,
  emptyVnets: `resources | where type =~ "microsoft.network/virtualnetworks" | where properties.subnets == "[]" | project id, name, location, resourceGroup, subscriptionId`,
  emptySubnets: `resources | where type =~ "microsoft.network/virtualnetworks" | extend subnet = properties.subnets | mv-expand subnet | extend ipConfigurations = subnet.properties.ipConfigurations | extend delegations = subnet.properties.delegations | extend applicationGatewayIPConfigurations = subnet.properties.applicationGatewayIPConfigurations | where isnull(ipConfigurations) and delegations == "[]" and isnull(applicationGatewayIPConfigurations) | extend SubnetName = tostring(subnet.name), SubnetId = tostring(subnet.id) | project id=SubnetId, name=SubnetName, location, resourceGroup, subscriptionId`,
  natGateways: `Resources | where type =~ 'microsoft.network/natgateways' | where isnull(properties.subnets) or array_length(properties.subnets) == 0 | project id, name, location, resourceGroup, subscriptionId`,
  ipGroups: `resources | where type =~ "microsoft.network/ipgroups" | where properties.firewalls == "[]" and properties.firewallPolicies == "[]" | project id, name, location, resourceGroup, subscriptionId`,
  privateDnsZones: `resources | where type =~ "microsoft.network/privatednszones" | where properties.numberOfVirtualNetworkLinks == 0 | project id, name, location, resourceGroup, subscriptionId`,
  privateEndpoints: `resources | where type =~ "microsoft.network/privateendpoints" | extend connection = iff(array_length(properties.manualPrivateLinkServiceConnections) > 0, properties.manualPrivateLinkServiceConnections[0], properties.privateLinkServiceConnections[0]) | extend stateEnum = tostring(connection.properties.privateLinkServiceConnectionState.status) | where stateEnum == "Disconnected" | project id, name, location, resourceGroup, subscriptionId`,
  vnetGateways: `resources | where type =~ "microsoft.network/virtualnetworkgateways" | extend vpnClientConfiguration = properties.vpnClientConfiguration | extend Resource = id | join kind=leftouter (resources | where type =~ "microsoft.network/connections" | mv-expand Resource = pack_array(properties.virtualNetworkGateway1.id, properties.virtualNetworkGateway2.id) to typeof(string) | project Resource, connectionId = id) on Resource | where isempty(vpnClientConfiguration) and isempty(connectionId) | project id=Resource, name, location, resourceGroup, subscriptionId`,
  ddos: `resources | where type =~ "microsoft.network/ddosprotectionplans" | where isnull(properties.virtualNetworks) | project id, name, location, resourceGroup, subscriptionId`,
  emptyRgs: `ResourceContainers | where type =~ "microsoft.resources/subscriptions/resourcegroups" | extend rgAndSub = tolower(strcat(name, "--", subscriptionId)) | join kind=leftouter (Resources | extend rgAndSub = tolower(strcat(resourceGroup, "--", subscriptionId)) | summarize count() by rgAndSub) on rgAndSub | where isnull(count_) or count_ == 0 | project id, name, location, resourceGroup=name, subscriptionId`,
  apiConnections: `resources | where type =~ 'Microsoft.Web/connections' | project subscriptionId, Resource = id , name, resourceGroup, location | join kind = leftouter (resources | where type =~ 'microsoft.logic/workflows' | extend var_json = properties["parameters"]["$connections"]["value"] | mvexpand var_connection = var_json | where notnull(var_connection) | extend connectionId = extract("connectionId\\\":\\\"(.*?)\\\"", 1, tostring(var_connection)) | project connectionId) on $left.Resource == $right.connectionId | where connectionId == "" | project id=Resource, name, location, resourceGroup, subscriptionId`,
  expiredCerts: `resources | where type =~ 'microsoft.web/certificates' | extend expiresOn = todatetime(properties.expirationDate) | where expiresOn <= now() | project id, name, location, resourceGroup, subscriptionId`,
  emptySqlServers: `Resources | where type =~ 'microsoft.sql/servers' | project serverId = tolower(id), id, name, location, resourceGroup, subscriptionId | join kind=leftouter (Resources | where type =~ 'microsoft.sql/servers/databases' | extend serverId = tolower(extract("(?i)(^.+/servers/[^/]+)", 1, id)) | project dbId=id, serverId) on serverId | where isnull(dbId)`,
  stoppedFlexibleServers: `Resources | where type in~ ('microsoft.dbforpostgresql/flexibleservers', 'microsoft.dbformysql/flexibleservers') | where properties.state =~ 'Stopped' | project id, name, location, resourceGroup, subscriptionId`,
  emptyCosmosDbAccounts: `Resources | where type =~ 'microsoft.documentdb/databaseaccounts' | project accountId = tolower(id), id, name, location, resourceGroup, subscriptionId | join kind=leftouter (Resources | where type startswith 'microsoft.documentdb/databaseaccounts/' | extend accountId = tolower(extract("(?i)(^.+/databaseAccounts/[^/]+)", 1, id)) | project dbId=id, accountId) on accountId | where isnull(dbId)`,
  emptyEventHubNamespaces: `Resources | where type =~ 'microsoft.eventhub/namespaces' | project namespaceId = tolower(id), id, name, location, resourceGroup, subscriptionId | join kind=leftouter (Resources | where type =~ 'microsoft.eventhub/namespaces/eventhubs' | extend namespaceId = tolower(extract("(?i)(^.+/namespaces/[^/]+)", 1, id)) | project ehId=id, namespaceId) on namespaceId | where isnull(ehId)`,
  emptyServiceBusNamespaces: `Resources | where type =~ 'microsoft.servicebus/namespaces' | project namespaceId = tolower(id), id, name, location, resourceGroup, subscriptionId | join kind=leftouter (Resources | where type in~ ('microsoft.servicebus/namespaces/queues', 'microsoft.servicebus/namespaces/topics') | extend namespaceId = tolower(extract("(?i)(^.+/namespaces/[^/]+)", 1, id)) | project queueId=id, namespaceId) on namespaceId | where isnull(queueId)`,
  emptyApiManagement: `Resources | where type =~ 'microsoft.apimanagement/service' | project serviceId = tolower(id), id, name, location, resourceGroup, subscriptionId | join kind=leftouter (Resources | where type =~ 'microsoft.apimanagement/service/apis' | where name !endswith '/echo-api' | extend serviceId = tolower(extract("(?i)(^.+/service/[^/]+)", 1, id)) | project apiId=id, serviceId) on serviceId | where isnull(apiId)`,
  unprovisionedExpressRoute: `Resources | where type =~ 'microsoft.network/expressroutecircuits' | where properties.serviceProviderProvisioningState =~ 'NotProvisioned' or (array_length(properties.authorizations) == 0 and array_length(properties.peerings) == 0) | project id, name, location, resourceGroup, subscriptionId`,
  unattachedWafPolicies: `Resources | where type =~ 'microsoft.network/applicationgatewaywebapplicationfirewallpolicies' | where isnull(properties.applicationGateways) or array_length(properties.applicationGateways) == 0 | project id, name, location, resourceGroup, subscriptionId`,
  stoppedVirtualMachines: `Resources | where type =~ 'microsoft.compute/virtualmachines' | where properties.extended.instanceView.powerState.code in~ ('PowerState/deallocated', 'PowerState/stopped') | project id, name, location, resourceGroup, subscriptionId, powerState = tostring(properties.extended.instanceView.powerState.code)`,
  emptyAse: `Resources | where type =~ 'microsoft.web/hostingenvironments' | project aseId = tolower(id), id, name, location, resourceGroup, subscriptionId | join kind=leftouter (Resources | where type =~ 'microsoft.web/serverfarms' | extend aseId = tolower(properties.hostingEnvironmentProfile.id) | project farmId=id, aseId) on aseId | where isnull(farmId)`,

  expiredTtlResources: `Resources | where isnotempty(tags['ExpireOn']) or isnotempty(tags['TTL']) | project id, name, type, resourceGroup, tags, expirationDate = coalesce(tags['ExpireOn'], tags['TTL']), subscriptionId`,

  oldSnapshots: `Resources | where type =~ 'microsoft.compute/snapshots' | where properties.timeCreated < ago(30d) | project id, name, location, resourceGroup, subscriptionId, sizeGB=properties.diskSizeGB`,
  unusedLoadBalancers: `Resources | where type =~ 'microsoft.network/loadbalancers' | where isnull(properties.frontendIPConfigurations) or array_length(properties.frontendIPConfigurations) == 0 or isnull(properties.backendAddressPools) or array_length(properties.backendAddressPools) == 0 | project id, name, location, resourceGroup, subscriptionId`,
  unusedVNetGateways: `Resources | where type =~ 'microsoft.network/virtualnetworkgateways' | where isnull(properties.connections) or array_length(properties.connections) == 0 | project id, name, location, resourceGroup, subscriptionId`,
  // Application Gateways sin backend real: sin backend pools o con todos vacíos.
  // Un App GW facturando sin backend es gasto puro (colector del FinOps Toolkit).
  unusedAppGateways: `Resources | where type =~ 'microsoft.network/applicationgateways' | where isnull(properties.backendAddressPools) or array_length(properties.backendAddressPools) == 0 or isnull(properties.requestRoutingRules) or array_length(properties.requestRoutingRules) == 0 | project id, name, location, resourceGroup, subscriptionId, sku=tostring(properties.sku.name), tier=tostring(properties.sku.tier)`,
  longStoppedVMs: `Resources | where type =~ 'microsoft.compute/virtualmachines' | where properties.extended.instanceView.powerState.code == 'PowerState/deallocated' | project id, name, location, resourceGroup, subscriptionId, sku = properties.hardwareProfile.vmSize, osDiskId = properties.storageProfile.osDisk.managedDisk.id, dataDisks = properties.storageProfile.dataDisks`,
  unattachedPublicIps: `Resources | where type =~ 'microsoft.network/publicipaddresses' | where properties.ipConfiguration == '' or isnull(properties.ipConfiguration) | where properties.timeCreated < ago(14d) | project id, name, location, resourceGroup, subscriptionId, sku=sku.name`,
  unattachedNics: `Resources | where type =~ 'microsoft.network/networkinterfaces' | where isnull(properties.virtualMachine) | project id, name, location, resourceGroup, subscriptionId`,
  missingAhubWindowsVMs: `Resources | where type =~ 'microsoft.compute/virtualmachines' | where properties.storageProfile.osDisk.osType =~ 'Windows' and (isnull(properties.licenseType) or properties.licenseType != 'Windows_Server') | project id, name, location, resourceGroup, subscriptionId, sku = properties.hardwareProfile.vmSize`,
  missingAhubSql: `Resources | where type =~ 'microsoft.sql/servers/databases' and name !~ 'master'
    | where sku.tier in~ ('GeneralPurpose', 'BusinessCritical', 'Hyperscale')
    | where sku.name !startswith 'GP_S_'
    | where isnull(properties.licenseType) or properties.licenseType != 'BasePrice'
    | extend serverId = tostring(split(id, '/databases/')[0])
    | extend elasticPoolId = tostring(properties.elasticPoolId)
    | project id, name, location, resourceGroup, subscriptionId, sku = sku.name, tier = sku.tier, capacity = sku.capacity, serverId, elasticPoolId`,
  completelyUntaggedResources: `Resources | where isnull(tags) or isempty(tags) | project id, name, type, tags, location, resourceGroup, subscriptionId`,
  missingMandatoryTags: `Resources | where isnull(tags['Environment']) or isnull(tags['CostCenter']) | project id, name, type, tags, location, resourceGroup, subscriptionId`
};
